<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<nav aria-label="Yotpo Reviews Pagination">
  <ul class="pagination pagination-lg justify-content-center">
    <!-- <li class="page-item disabled"><a class="page-link" href="#"><b>&laquo;</b></a></li> -->
    <!-- <li class="page-item"><a class="page-link" href="#"><b>&lsaquo;</b></a></li> -->
    <li class="page-item">
      <a class="page-link" href="#" aria-label="First">
        <span aria-hidden="true"><b>&laquo;</b></span>
        <span class="sr-only">First</span>
      </a>
    <li class="page-item">
      <a class="page-link" href="#" aria-label="Previous">
        <span aria-hidden="true"><b>&lsaquo;</b></span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
    <li class="page-item active"><a class="page-link" href="#">1</a></li>
    <li class="page-item">
      <a class="page-link" href="#" aria-label="Next">
        <span aria-hidden="true"><b>&rsaquo;</b></span>
        <span class="sr-only">Next</span>
      </a>
    <li class="page-item">
      <a class="page-link" href="#" aria-label="Last">
        <span aria-hidden="true"><b>&raquo;</b></span>
        <span class="sr-only">Last</span>
      </a>
    </li>
    <!-- <li class="page-item"><a class="page-link" href="#"><b>&rsaquo;</b></a></li> -->
    <!-- <li class="page-item"><a class="page-link" href="#"><b>&raquo;</b></a></li> -->
  </ul>
</nav>