<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('Integration_Yotpo::css/styles.css'); ?>">

<script type="text/javascript" src="<?php echo $block->getViewFileUrl('Integration_Yotpo::js/review.js'); ?>"></script>>
<!-- <div><h3><b>Yotpo Reviews</b></h3></div> -->
<div class="review-content-box jumbotron container-fluid">
    <?php 
        // $totalPages = $block->getTotalPageCount();
        $page = $block->getRequest()->getParam('page') ?: 1; 
        $count = $block->getRequest()->getParam('count') ?: 5; 
        // $page = ($page <= $totalPages) ? $page : $totalPages;
        $reviewsCollection = $block->getAllReviews($page, $count);
        if ($reviewsCollection['code'] && count($reviewsCollection['body']['reviews'])):
            foreach ($reviewsCollection['body']['reviews'] as $key => $review):?>
                <div class="content-holder card">
                    <div class="reviewer"><?= $review['name'] ?></div>
                    <div class="title"><b><?= $review['title'] ?></b></div>
                    <div class="ratings"><i>Ratings : <?= $review['score'] ?>/5</i></div>
                    <div class="sku">Sku: <?php
                        if ($block->getProductUrl($review['sku'])): ?>
                            <a href="<?= $block->getProductUrl($review['sku']) ?>"><?= $review['sku'] ?></a><?php 
                        else:  
                            echo $review['sku']; 
                        endif; ?>
                    </div>
                    <div class="description"><p class="content"><?= $review['content'] ?></p></div>
                </div>
            <?php endforeach; 
        else: ?> 
            <div class="no-result">
                <b><h3>404 review not found</h3></b>
            </div> <?php
        endif;    
    ?>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif; ?>
</div>



<nav aria-label="Yotpo Reviews Pagination">
    <ul class="pagination pagination-lg justify-content-center"> <?php

    if ($page > 2): ?>    
        <li class="page-item">
          <a data-item="yotpo-reviews-pagination" class="page-link" href="?page=1&count=<?= $count ?>" aria-label="First">
            <span aria-hidden="true"><b>&laquo;</b></span>
            <span class="sr-only">First</span>
          </a>
        </li> <?php
    endif;
    if ($page > 1): ?>
        <li class="page-item">
            <a data-item="yotpo-reviews-pagination" class="page-link" href="?page=<?= $page-1 ?>&count=<?= $count ?>" aria-label="Previous"> <?php
    else: ?>
        <li class="page-item disabled">
            <a data-item="yotpo-reviews-pagination" class="page-link" href="#" aria-label="Previous"> <?php
    endif; ?>
                <span aria-hidden="true"><b>&lsaquo;</b></span>
                <span class="sr-only">Previous</span>
            </a>
        </li>

        <li class="page-item active"><a data-item="yotpo-reviews-pagination" class="page-link" href="?page=<?= $page ?>&count=<?= $count ?>"><?= $page ?></a></li> <?php

    // if ($page < $totalPages): ?>
        <li class="page-item">
            <a data-item="yotpo-reviews-pagination" class="page-link" href="?page=<?= $page+1 ?>&count=<?= $count ?>" aria-label="Next"> <?php
    // else: ?>
        <!-- <li class="page-item disabled"> -->
            <!-- <a class="page-link" href="#" aria-label="Next"> --> <?php 
    // endif; ?>
                <span aria-hidden="true"><b>&rsaquo;</b></span>
                <span class="sr-only">Next</span>
            </a>
        </li>

    <!-- <li class="page-item">
      <a class="page-link" href="#" aria-label="Last">
        <span aria-hidden="true"><b>&raquo;</b></span>
        <span class="sr-only">Last</span>
      </a>
    </li> -->

  </ul>
</nav>